# Generated by Django 2.2.2 on 2019-07-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_coments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coments',
            options={'verbose_name': 'Coment', 'verbose_name_plural': 'Coments'},
        ),
        migrations.AddField(
            model_name='coments',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date:time'),
        ),
        migrations.AddField(
            model_name='coments',
            name='moderation',
            field=models.BooleanField(default=False),
        ),
    ]
