# Generated by Django 2.2.2 on 2019-07-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_comments_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.EmailField(max_length=42, null=True),
        ),
    ]
