# Generated by Django 2.2.2 on 2019-07-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_comments_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.CharField(blank=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='email',
            field=models.EmailField(blank=True, default=1, max_length=42),
            preserve_default=False,
        ),
    ]
