version: '3.1'

services:

  db:
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./databases:/var/lib/mysql"

  adminer:
    build: ./adminer
    restart: always
    ports:
      - 6080:8080
